### PR TITLE
add editable option to starrating widget

### PR DESCRIPTION
**Pull request by manumaticx**
You may want to disable the opportunity to change the rating value but only display a rating.

### CODE REVIEW

**Comment by ma2kubo** [comment]
Evernote was unable to submit your note for the following reason:

The emailed note was received, but Evernote did not understand the email address. It may have been mistyped, or the user may not exist. Please check to make sure the address was properly entered.

Original message information:

**Comment by skypanther** [comment]
Thanks! This is a fine idea, but I'd rather have the stars clickable by default. So, your if clause would be `if(!args.editable)`. Thoughts?

**Comment by ma2kubo** [comment]
Evernote was unable to submit your note for the following reason:

The emailed note was received, but Evernote did not understand the email address. It may have been mistyped, or the user may not exist. Please check to make sure the address was properly entered.

Original message information:

**Comment by manumaticx** [comment]
@skypanther Agreed! I've added the `!`

**Comment by ma2kubo** [comment]
Evernote was unable to submit your note for the following reason:

The emailed note was received, but Evernote did not understand the email address. It may have been mistyped, or the user may not exist. Please check to make sure the address was properly entered.

Original message information:

**Comment by skypanther** [comment]
Wonderful, thanks for the improvement.

**Pull request merged**
